# Dependencies
gems:             [jekyll-gist]
markdown:         kramdown
highlighter:      pygments
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hi!
# tagline:          'A Jekyll theme'
description:      'I am <b>Debora Caldarola</b>.<br>Welcome to my personal page.'
url:              https://debcaldarola.github.io
baseurl:          /

author:
  name:           'Debora Caldarola'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          June 2025

github:
  repo:           https://github.com/debcaldarola
